### PR TITLE
[LA.UM.8.2.1.r1] Bump to latest LA.UM.8.2.1.r1-04700-sdm660.0 tag

### PR DESCRIPTION
**Pull request by MarijnS95**
@haxk20 Let us know when this is tested and ready for merge :grin:

### CODE REVIEW

**Comment by Haxk20** [comment]
Sir Yes Sir.
On more serious note will do once i can.

**Comment by Haxk20** [comment]
Safe to merge. See no regressions.

Edit: do not merge. Breaks video playback.

**Comment by Haxk20** [comment]
Do not merge. Video decoding is broken.

**Comment by MarijnS95** [comment]
@Haxk20 A new `LA.UM.8.2.1.r1-04700-sdm660.0` tag appeared. Would you mind to check if that fixes the issue, and otherwise do a bisect to point out the broken commit?

Otherwise I'll have a look myself on a Ningles, too.

**Comment by kholk** [comment]
Go for the newer SDM660 tag directly.

This pr cannot be merged as it is, nor with the new SDM660 tag. 
Anything newer than what we currently have for SDM660 requires a kernel driver update (check the newer tags for sdm660 4.14 and cherry-pick the vidc patches to the kernel). 

Media updates for sdm660 shall be merged ONLY with their related vidc_3x kernel driver update.

**Comment by Haxk20** [comment]
@MarijnS95 yup can do so tomorrow maybe I can do the kernel side too

**Pull request merged**
